{
  "blocks": [
    {
      "category": "Кнопки",
      "html": "<script src=\"https://unpkg.com/@phosphor-icons/web\"></script>\n\n<div class=\"container\">\n  <button class=\"button\" type=\"button\">Копировать код</button>\n</div>\n\n<style>\n/* Контейнер для центрирования */\n.container {\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  min-height: 100vh; /* Занимает всю высоту экрана */\n  width: 100%;\n}\n\n@import url('https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700&display=swap');\n\n.button {\n  position: relative;\n  border: 1px solid transparent;\n  border-radius: 6px;\n  padding: 8px 16px;\n  width: 250px; /* Фиксированная ширина */\n  height: 65px; /* Фиксированная высота */\n  min-width: auto; /* Убираем минимальную ширину, так как задана фиксированная */\n  text-align: center;\n  color: #fff; /* Белый цвет текста */\n  font-family: 'Manrope', sans-serif; /* Шрифт Manrope */\n  font-weight: 600;\n  font-size: 16px;\n  background-image: linear-gradient(to bottom, #2563eb, #1d4ed8, #1e40af), linear-gradient(to bottom, #1e40af, #1e3a8a); /* Синий градиент */\n  background-clip: padding-box, border-box;\n  background-origin: padding-box, border-box;\n  box-shadow: inset 0 1px rgba(255, 255, 255, 0.25), inset 0 -1px rgba(0, 0, 0, 0.1), 0 2px 4px rgba(0, 0, 0, 0.25);\n  cursor: pointer;\n  /* Убраны transition и will-change для отключения эффектов hover */\n}\n\n/* Убраны все эффекты при наведении и нажатии */\n.button:active,\n.button:hover,\n.button:focus {\n  transform: none;\n  filter: none;\n  color: #fff; /* Фиксируем белый цвет текста при наведении */\n  background-image: linear-gradient(to bottom, #2563eb, #1d4ed8, #1e40af), linear-gradient(to bottom, #1e40af, #1e3a8a); /* Фиксируем градиент */\n}\n\n.button::after {\n  --overflow-x: 4px;\n  --snow-image: url(\"https://assets.codepen.io/4175254/snow-cap-test-2.png\");\n  content: \"\";\n  position: absolute;\n  top: -6px;\n  left: calc(var(--overflow-x) * -1);\n  border-image-source: var(--snow-image);\n  border-image-slice: calc(6 * 56 / 20) fill;\n  border-image-width: calc(28px / 3);\n  border-image-repeat: round;\n  width: calc(100% + var(--overflow-x) * 2);\n  height: 28px;\n  filter: drop-shadow(0 2px 1px rgba(0, 0, 0, 0.25));\n  opacity: 1;\n}\n</style>",
      "id": "user_1790442820012",
      "title": "Кнопка Новый год"
    }
  ]
}